run:
  deadline: 10m

linters:
  enable:
    - contextcheck
    - gocritic
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert

linters-settings:
  goimports:
    local-prefixes: github.com/NVIDIA/nvidia-container-toolkit

issues:
  exclude:
  # The legacy hook relies on spec.Hooks.Prestart, which is deprecated as of the v1.2.0 OCI runtime spec.
  - "SA1019:(.+).Prestart is deprecated(.+)"
  # TODO: We should address each of the following integer overflows.
  - "G115: integer overflow conversion(.+)"
  exclude-rules:
  # Exclude the gocritic dupSubExpr issue for cgo files.
  - path: internal/dxcore/dxcore.go
    linters:
    - gocritic
    text: dupSubExpr
  # Exclude the checks for usage of returns to config.Delete(Path) in the crio and containerd config packages.
  - path: pkg/config/engine/
    linters:
    - errcheck
    text: config.Delete
