// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package nvcdi

import (
	"sync"

	"github.com/NVIDIA/go-nvlib/pkg/nvlib/info"
)

// Ensure, that infoInterfaceMock does implement infoInterface.
// If this is not the case, regenerate this file with moq.
var _ infoInterface = &infoInterfaceMock{}

// infoInterfaceMock is a mock implementation of infoInterface.
//
//	func TestSomethingThatUsesinfoInterface(t *testing.T) {
//
//		// make and configure a mocked infoInterface
//		mockedinfoInterface := &infoInterfaceMock{
//			HasDXCoreFunc: func() (bool, string) {
//				panic("mock out the HasDXCore method")
//			},
//			HasNvmlFunc: func() (bool, string) {
//				panic("mock out the HasNvml method")
//			},
//			HasOnlyIntegratedGPUsFunc: func() (bool, string) {
//				panic("mock out the HasOnlyIntegratedGPUs method")
//			},
//			HasTegraFilesFunc: func() (bool, string) {
//				panic("mock out the HasTegraFiles method")
//			},
//			IsTegraSystemFunc: func() (bool, string) {
//				panic("mock out the IsTegraSystem method")
//			},
//			ResolvePlatformFunc: func() info.Platform {
//				panic("mock out the ResolvePlatform method")
//			},
//			UsesOnlyNVGPUModuleFunc: func() (bool, string) {
//				panic("mock out the UsesOnlyNVGPUModule method")
//			},
//		}
//
//		// use mockedinfoInterface in code that requires infoInterface
//		// and then make assertions.
//
//	}
type infoInterfaceMock struct {
	// HasDXCoreFunc mocks the HasDXCore method.
	HasDXCoreFunc func() (bool, string)

	// HasNvmlFunc mocks the HasNvml method.
	HasNvmlFunc func() (bool, string)

	// HasOnlyIntegratedGPUsFunc mocks the HasOnlyIntegratedGPUs method.
	HasOnlyIntegratedGPUsFunc func() (bool, string)

	// HasTegraFilesFunc mocks the HasTegraFiles method.
	HasTegraFilesFunc func() (bool, string)

	// IsTegraSystemFunc mocks the IsTegraSystem method.
	IsTegraSystemFunc func() (bool, string)

	// ResolvePlatformFunc mocks the ResolvePlatform method.
	ResolvePlatformFunc func() info.Platform

	// UsesOnlyNVGPUModuleFunc mocks the UsesOnlyNVGPUModule method.
	UsesOnlyNVGPUModuleFunc func() (bool, string)

	// calls tracks calls to the methods.
	calls struct {
		// HasDXCore holds details about calls to the HasDXCore method.
		HasDXCore []struct {
		}
		// HasNvml holds details about calls to the HasNvml method.
		HasNvml []struct {
		}
		// HasOnlyIntegratedGPUs holds details about calls to the HasOnlyIntegratedGPUs method.
		HasOnlyIntegratedGPUs []struct {
		}
		// HasTegraFiles holds details about calls to the HasTegraFiles method.
		HasTegraFiles []struct {
		}
		// IsTegraSystem holds details about calls to the IsTegraSystem method.
		IsTegraSystem []struct {
		}
		// ResolvePlatform holds details about calls to the ResolvePlatform method.
		ResolvePlatform []struct {
		}
		// UsesOnlyNVGPUModule holds details about calls to the UsesOnlyNVGPUModule method.
		UsesOnlyNVGPUModule []struct {
		}
	}
	lockHasDXCore             sync.RWMutex
	lockHasNvml               sync.RWMutex
	lockHasOnlyIntegratedGPUs sync.RWMutex
	lockHasTegraFiles         sync.RWMutex
	lockIsTegraSystem         sync.RWMutex
	lockResolvePlatform       sync.RWMutex
	lockUsesOnlyNVGPUModule   sync.RWMutex
}

// HasDXCore calls HasDXCoreFunc.
func (mock *infoInterfaceMock) HasDXCore() (bool, string) {
	callInfo := struct {
	}{}
	mock.lockHasDXCore.Lock()
	mock.calls.HasDXCore = append(mock.calls.HasDXCore, callInfo)
	mock.lockHasDXCore.Unlock()
	if mock.HasDXCoreFunc == nil {
		var (
			bOut bool
			sOut string
		)
		return bOut, sOut
	}
	return mock.HasDXCoreFunc()
}

// HasDXCoreCalls gets all the calls that were made to HasDXCore.
// Check the length with:
//
//	len(mockedinfoInterface.HasDXCoreCalls())
func (mock *infoInterfaceMock) HasDXCoreCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockHasDXCore.RLock()
	calls = mock.calls.HasDXCore
	mock.lockHasDXCore.RUnlock()
	return calls
}

// HasNvml calls HasNvmlFunc.
func (mock *infoInterfaceMock) HasNvml() (bool, string) {
	callInfo := struct {
	}{}
	mock.lockHasNvml.Lock()
	mock.calls.HasNvml = append(mock.calls.HasNvml, callInfo)
	mock.lockHasNvml.Unlock()
	if mock.HasNvmlFunc == nil {
		var (
			bOut bool
			sOut string
		)
		return bOut, sOut
	}
	return mock.HasNvmlFunc()
}

// HasNvmlCalls gets all the calls that were made to HasNvml.
// Check the length with:
//
//	len(mockedinfoInterface.HasNvmlCalls())
func (mock *infoInterfaceMock) HasNvmlCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockHasNvml.RLock()
	calls = mock.calls.HasNvml
	mock.lockHasNvml.RUnlock()
	return calls
}

// HasOnlyIntegratedGPUs calls HasOnlyIntegratedGPUsFunc.
func (mock *infoInterfaceMock) HasOnlyIntegratedGPUs() (bool, string) {
	callInfo := struct {
	}{}
	mock.lockHasOnlyIntegratedGPUs.Lock()
	mock.calls.HasOnlyIntegratedGPUs = append(mock.calls.HasOnlyIntegratedGPUs, callInfo)
	mock.lockHasOnlyIntegratedGPUs.Unlock()
	if mock.HasOnlyIntegratedGPUsFunc == nil {
		var (
			bOut bool
			sOut string
		)
		return bOut, sOut
	}
	return mock.HasOnlyIntegratedGPUsFunc()
}

// HasOnlyIntegratedGPUsCalls gets all the calls that were made to HasOnlyIntegratedGPUs.
// Check the length with:
//
//	len(mockedinfoInterface.HasOnlyIntegratedGPUsCalls())
func (mock *infoInterfaceMock) HasOnlyIntegratedGPUsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockHasOnlyIntegratedGPUs.RLock()
	calls = mock.calls.HasOnlyIntegratedGPUs
	mock.lockHasOnlyIntegratedGPUs.RUnlock()
	return calls
}

// HasTegraFiles calls HasTegraFilesFunc.
func (mock *infoInterfaceMock) HasTegraFiles() (bool, string) {
	callInfo := struct {
	}{}
	mock.lockHasTegraFiles.Lock()
	mock.calls.HasTegraFiles = append(mock.calls.HasTegraFiles, callInfo)
	mock.lockHasTegraFiles.Unlock()
	if mock.HasTegraFilesFunc == nil {
		var (
			bOut bool
			sOut string
		)
		return bOut, sOut
	}
	return mock.HasTegraFilesFunc()
}

// HasTegraFilesCalls gets all the calls that were made to HasTegraFiles.
// Check the length with:
//
//	len(mockedinfoInterface.HasTegraFilesCalls())
func (mock *infoInterfaceMock) HasTegraFilesCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockHasTegraFiles.RLock()
	calls = mock.calls.HasTegraFiles
	mock.lockHasTegraFiles.RUnlock()
	return calls
}

// IsTegraSystem calls IsTegraSystemFunc.
func (mock *infoInterfaceMock) IsTegraSystem() (bool, string) {
	callInfo := struct {
	}{}
	mock.lockIsTegraSystem.Lock()
	mock.calls.IsTegraSystem = append(mock.calls.IsTegraSystem, callInfo)
	mock.lockIsTegraSystem.Unlock()
	if mock.IsTegraSystemFunc == nil {
		var (
			bOut bool
			sOut string
		)
		return bOut, sOut
	}
	return mock.IsTegraSystemFunc()
}

// IsTegraSystemCalls gets all the calls that were made to IsTegraSystem.
// Check the length with:
//
//	len(mockedinfoInterface.IsTegraSystemCalls())
func (mock *infoInterfaceMock) IsTegraSystemCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockIsTegraSystem.RLock()
	calls = mock.calls.IsTegraSystem
	mock.lockIsTegraSystem.RUnlock()
	return calls
}

// ResolvePlatform calls ResolvePlatformFunc.
func (mock *infoInterfaceMock) ResolvePlatform() info.Platform {
	callInfo := struct {
	}{}
	mock.lockResolvePlatform.Lock()
	mock.calls.ResolvePlatform = append(mock.calls.ResolvePlatform, callInfo)
	mock.lockResolvePlatform.Unlock()
	if mock.ResolvePlatformFunc == nil {
		var (
			platformOut info.Platform
		)
		return platformOut
	}
	return mock.ResolvePlatformFunc()
}

// ResolvePlatformCalls gets all the calls that were made to ResolvePlatform.
// Check the length with:
//
//	len(mockedinfoInterface.ResolvePlatformCalls())
func (mock *infoInterfaceMock) ResolvePlatformCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockResolvePlatform.RLock()
	calls = mock.calls.ResolvePlatform
	mock.lockResolvePlatform.RUnlock()
	return calls
}

// UsesOnlyNVGPUModule calls UsesOnlyNVGPUModuleFunc.
func (mock *infoInterfaceMock) UsesOnlyNVGPUModule() (bool, string) {
	callInfo := struct {
	}{}
	mock.lockUsesOnlyNVGPUModule.Lock()
	mock.calls.UsesOnlyNVGPUModule = append(mock.calls.UsesOnlyNVGPUModule, callInfo)
	mock.lockUsesOnlyNVGPUModule.Unlock()
	if mock.UsesOnlyNVGPUModuleFunc == nil {
		var (
			bOut bool
			sOut string
		)
		return bOut, sOut
	}
	return mock.UsesOnlyNVGPUModuleFunc()
}

// UsesOnlyNVGPUModuleCalls gets all the calls that were made to UsesOnlyNVGPUModule.
// Check the length with:
//
//	len(mockedinfoInterface.UsesOnlyNVGPUModuleCalls())
func (mock *infoInterfaceMock) UsesOnlyNVGPUModuleCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockUsesOnlyNVGPUModule.RLock()
	calls = mock.calls.UsesOnlyNVGPUModule
	mock.lockUsesOnlyNVGPUModule.RUnlock()
	return calls
}
