FROM quay.io/centos/centos:stream8

RUN sed -i -e "s|mirrorlist=|#mirrorlist=|g" \
               -e "s|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g" \
                  /etc/yum.repos.d/CentOS-Stream-*

RUN yum install -y createrepo rpm-sign pinentry
